# Generated by Django 6.0.3 on 2026-03-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
