# Generated by Django 6.0.3 on 2026-03-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='hours',
            field=models.FloatField(default=0),
        ),
    ]
