# Generated by Django 6.0.3 on 2026-03-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_topic_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='color',
            field=models.CharField(default='#4E4E4E', max_length=10),
        ),
    ]
