# Generated by Django 6.0.3 on 2026-03-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_register_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='color',
        ),
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(default='#4E4E4E', max_length=10),
        ),
    ]
