# Generated by Django 6.0.3 on 2026-04-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_register_created_at_topic_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='student',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
