# Generated by Django 6.0.3 on 2026-04-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='commentary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
