# Generated by Django 6.0.3 on 2026-04-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_API', '0003_register_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='feedback',
            field=models.IntegerField(default=-1),
        ),
    ]
