# Generated by Django 6.0.3 on 2026-04-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_API', '0004_alter_register_feedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('student', 'name')},
        ),
    ]
