# Generated by Django 6.0.3 on 2026-04-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_API', '0005_alter_topic_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='see',
            field=models.BooleanField(default=True),
        ),
    ]
