# Generated by Django 6.0.3 on 2026-04-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_API', '0006_topic_see'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='see',
        ),
        migrations.AddField(
            model_name='register',
            name='see',
            field=models.BooleanField(default=True),
        ),
    ]
