# Generated by Django 6.0.3 on 2026-04-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_API', '0007_remove_topic_see_register_see'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
