# Generated by Django 6.0.3 on 2026-04-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_API', '0008_register_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='registers',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
    ]
