# Generated by Django 6.0.3 on 2026-04-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_API', '0009_alter_register_table_alter_student_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
