# Generated by Django 6.0.3 on 2026-04-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_API', '0010_alter_topic_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
