# Generated by Django 6.0.3 on 2026-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_API', '0011_alter_register_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
